package testException;

public class Main {

	public static void main(String[] args) {
	
		int x = 0;
		int y = 5/x;
		System.out.print(x);
		System.out.println("Fin de calcul");
			


	}

}
