package testException;

public class Main {

	public static void main(String[] args) {
	
		int x=0,y=5;
		try {
			System.out.println(y/x);
		}
		catch (Exception e) {
			System.out.println("Exception : Division par zero ");
		}
		System.out.println("Fin de calcul");
			


	}

}
