package testException;

public class Main {

	public static void main(String[] args) {
	
//		int x=0,y=5;
//		try {
//			System.out.println(y/x);
//		}
//		catch (Exception e) {
//			System.out.println("Exception : " + e.getMessage());
//			e.printStackTrace();
//		}
//		System.out.println("Fin de calcul");
			
		Adresse a = null;
		try {a = new Adresse ("paradis", "Marseille","13006");}
		catch(IncorrectCodePostalException | IncorrectStreetNameException e) {e.printStackTrace();}
	}

}
